# Generated by Django 2.2.1 on 2019-05-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_remove_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
    ]
