# Generated by Django 2.2.1 on 2019-05-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_remove_user_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Disease',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Citie'},
        ),
    ]
