# Generated by Django 2.2.1 on 2019-05-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_auto_20190504_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disease',
            new_name='Symptoms',
        ),
    ]
