# Generated by Django 2.2.1 on 2019-05-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0006_auto_20190505_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptoms',
            options={'ordering': ['name'], 'verbose_name': 'Symptom'},
        ),
    ]
