# Generated by Django 2.2.1 on 2019-05-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0007_auto_20190505_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptoms',
            options={'verbose_name': 'Symptom'},
        ),
    ]
